name: number_pagination
description: Pagination using numbers, similar to the classic web-style pagination. Explore pages by numbers, not infinite scrolling!

version: 1.1.6
homepage: https://github.com/xpwmaosldk/number_pagination

screenshots:
  - description: "It demonstrates how it works during initialization."
    path: screenshots/screenshots1.webp
  - description: "It shows the functionality when the 1 button is pressed."
    path: screenshots/screenshots2.webp

environment:
  sdk: ">=3.0.0 <4.0.0"
  # flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# flutter:

topics:
  - page
  - paging
  - web
